version: '3'
services:
  postgres:
    image: "postgres:$postgres_version"
    container_name: ${container_name}_postgres
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - "$data_path/postgres:/var/lib/postgresql/data"
  odoo:
    build:
      context: ../../dockerfiles/custom/
      args:
        - id=$id
        - odoo_version=$odoo_version
    external_links:
      - postgres
    depends_on:
      - postgres
    container_name: $container_name
    volumes:
      - $addons_path:/opt/odoo/custom/addons
      - $etc_path:/opt/odoo/custom/etc
      - $data_path:/opt/odoo/data
      - $sources_path:/opt/odoo/sources
    command: tail -f /dev/null
    restart: on-failure
    ports:
      - "$port:8069"
    cap_add:
      - SYS_PTRACE
